### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by jj09** [dotNetConfPL/dotNetConfPL.Web#24]
No SSL cert and https://dotnetconf.pl/ shows 404.
Who owns the domain?
Website is on my Azure and deployed through github.
Don't remember how SSL was configured. I think Azure provide them for free?
@pawlos you have access to that website per my Azure - LMK if you need my help

**Comment by pawlos** [comment]
@jj09 I'll clean this, but I think it's not longer holds it's purpose so I'll just tear down things.
